import streamlit as st
from PIL import Image, ImageDraw, ImageFont
import textwrap
import io
import base64

# -------------------- Helper Functions --------------------

def create_poster(title, content, theme="default"):
    width, height = 600, 900
    bg_color, text_color, accent_color = (255, 255, 255), (0, 0, 0), (0, 0, 0)

    # Thematic colors
    if theme == "health":
        bg_color = (240, 248, 255)      # AliceBlue
        text_color = (0, 100, 0)        # DarkGreen
        accent_color = (0, 128, 0)      # Green
    elif theme == "tech":
        bg_color = (245, 245, 245)      # Light Gray
        text_color = (25, 25, 112)      # MidnightBlue
        accent_color = (0, 0, 128)      # Navy
    elif theme == "travel":
        bg_color = (255, 248, 220)      # Cornsilk
        text_color = (139, 69, 19)      # SaddleBrown
        accent_color = (165, 42, 42)    # Brown

    # Create blank image
    img = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(img)

    # Load font
    try:
        title_font = ImageFont.truetype("arialbd.ttf", 40)
        body_font = ImageFont.truetype("arial.ttf", 18)
    except IOError:
        title_font = ImageFont.load_default()
        body_font = ImageFont.load_default()

    # Title
    draw.text((width // 2, 80), title, fill=text_color, font=title_font, anchor="mm")

    # Subtitle
    subtitle = f"Topic: {title}"
    draw.text((width // 2, 130), subtitle, fill=accent_color, font=body_font, anchor="mm")

    # Wrap content
    margin = 50
    max_width = width - 2 * margin
    char_width = body_font.getlength("A")
    max_chars = int(max_width // char_width)
    lines = textwrap.wrap(content, width=max_chars)

    y = 180
    for line in lines:
        draw.text((margin, y), line, fill=text_color, font=body_font)
        y += 25

    # Footer
    draw.rectangle([0, height-50, width, height], fill=accent_color)
    draw.text((width // 2, height-25), "Generated by AI Poster App", fill=bg_color, font=body_font, anchor="mm")

    return img

def get_image_download_link(img, filename="poster.png"):
    buffered = io.BytesIO()
    img.save(buffered, format="PNG")
    b64 = base64.b64encode(buffered.getvalue()).decode()
    href = f'<a href="data:image/png;base64,{b64}" download="{filename}">📥 Download Poster</a>'
    return href

# -------------------- Streamlit UI --------------------

st.title("🖼️ Poster Generator App")
st.write("Generate a poster image from a topic and short text.")

title = st.text_input("Enter Poster Title", "Health")
content = st.text_area("Enter Poster Content", "Health is wealth. Eating well, exercising regularly, and sleeping adequately form the foundation of a healthy lifestyle.")
theme = st.selectbox("Select Theme", ["default", "health", "tech", "travel"])

if st.button("Generate Poster"):
    poster_img = create_poster(title, content, theme)
    st.image(poster_img, caption="Your Poster", use_column_width=True)

    # Show download link
    st.markdown(get_image_download_link(poster_img), unsafe_allow_html=True)
