import streamlit as st
import pandas as pd
from transformers import T5Tokenizer, T5ForConditionalGeneration
from PIL import Image, ImageDraw, ImageFont
import textwrap
from io import BytesIO
import base64
import os

# Initialize the model and tokenizer
@st.cache_resource
def load_model():
    tokenizer = T5Tokenizer.from_pretrained("t5-small")
    model = T5ForConditionalGeneration.from_pretrained("t5-small")
    return tokenizer, model

tokenizer, model = load_model()

# Sample data
data = {
    "title": ["Health", "Tech", "Travel"],
    "description": [
        "Health, a state of complete well-being, transcends the mere absence of disease...",
        "Technology is advancing at an unprecedented pace, shaping industries and everyday life...",
        "Travel is undergoing a transformation as sustainability and personalization become key trends..."
    ]
}
df = pd.DataFrame(data)

def generate_blog_content(topic, description):
    """Generate blog content using T5 model"""
    input_text = f"write a 100-word blog post about {topic}: {description}"
    input_ids = tokenizer.encode(input_text, return_tensors="pt", max_length=512, truncation=True)
    outputs = model.generate(input_ids, max_length=200, num_beams=4, early_stopping=True)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def create_poster(title, content, theme="health", small=True):
    base_width, base_height = 600, 900
    scale_factor = 0.75 if small else 1
    width, height = int(base_width * scale_factor), int(base_height * scale_factor)

    # Theme colors
    if theme == "health":
        bg_color = (240, 248, 255)
        text_color = (0, 100, 0)
        accent_color = (0, 128, 0)
    elif theme == "tech":
        bg_color = (240, 240, 240)
        text_color = (25, 25, 112)
        accent_color = (0, 0, 128)
    else:
        bg_color = (255, 248, 220)
        text_color = (139, 69, 19)
        accent_color = (165, 42, 42)

    img = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(img)

    border_size = int(20 * scale_factor)
    draw.rectangle([border_size, border_size, width-border_size, height-border_size],
                   outline=accent_color, width=int(3 * scale_factor))

    try:
        title_font = ImageFont.truetype("arialbd.ttf", int(40 * scale_factor))
        subtitle_font = ImageFont.truetype("arial.ttf", int(20 * scale_factor))
        body_font = ImageFont.truetype("arial.ttf", int(16 * scale_factor))
    except IOError:
        title_font = ImageFont.load_default()
        subtitle_font = ImageFont.load_default()
        body_font = ImageFont.load_default()

    draw.text((width//2, int(75 * scale_factor)), title, fill=text_color, font=title_font, anchor="mm")
    subtitle = f"Latest Trends in {title}"
    draw.text((width//2, int(125 * scale_factor)), subtitle, fill=accent_color, font=subtitle_font, anchor="mm")

    text_width = width - 2 * int(50 * scale_factor)
    char_width = body_font.getlength("A")
    max_chars_per_line = int(text_width // char_width)
    lines = textwrap.wrap(content, width=max_chars_per_line)
    y_position = int(175 * scale_factor)
    line_height = int(20 * scale_factor)

    for line in lines:
        draw.text((int(50 * scale_factor), y_position), line, fill=text_color, font=body_font)
        y_position += line_height

    footer_height = int(50 * scale_factor)
    draw.rectangle([0, height-footer_height, width, height], fill=accent_color)
    draw.text((width//2, height-int(25 * scale_factor)), "Generated by AI Blog Poster",
              fill=bg_color, font=subtitle_font, anchor="mm")

    return img

def image_download_link(img, filename):
    buffered = BytesIO()
    img.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode()

    href = f'<a href="data:image/png;base64,{img_str}" download="{filename}">📥 Download Poster</a>'
    return href

# Streamlit UI
st.title("🧠 AI Blog Poster Generator")
st.write("This app generates a mini blog post and poster using T5 and Streamlit.")

selected_topic = st.selectbox("Choose a topic", df["title"])

if st.button("Generate Poster"):
    selected_row = df[df["title"] == selected_topic].iloc[0]
    blog_content = generate_blog_content(selected_row["title"], selected_row["description"])
    theme = selected_row["title"].lower()
    poster = create_poster(selected_row["title"], blog_content, theme=theme, small=True)

    st.image(poster, caption=f"{selected_topic} Poster", use_column_width=True)
    st.markdown(image_download_link(poster, f"{theme}_poster.png"), unsafe_allow_html=True)
