import pandas as pd
from transformers import T5Tokenizer, T5ForConditionalGeneration
from PIL import Image, ImageDraw, ImageFont
import textwrap
import os
from io import BytesIO
import base64
import streamlit as st

# Load dataset
data = {
    "title": ["Health", "Tech", "Travel"],
    "description": [
        "Health, a state of complete well-being, transcends the mere absence of disease. It's a dynamic equilibrium of physical, mental, and social vitality, a cornerstone of a fulfilling existence. Our bodies, intricate machines, require nourishment, movement, and rest to function optimally. A balanced diet, rich in fruits, vegetables, and whole grains, fuels our cells and bolsters our defenses. Regular physical activity, from brisk walks to vigorous workouts, strengthens our muscles, improves cardiovascular health, and elevates our mood. Sufficient sleep, a nightly restorative ritual, allows our bodies and minds to repair and rejuvenate..",
        "Technology is advancing at an unprecedented pace, shaping industries and everyday life...",
        "Travel is undergoing a transformation as sustainability and personalization become key trends..."
    ]
}
df = pd.DataFrame(data)

# Initialize T5 model for text generation
tokenizer = T5Tokenizer.from_pretrained("t5-small")
model = T5ForConditionalGeneration.from_pretrained("t5-small")

def generate_blog_content(topic, description):
    """Generate blog content using T5 model"""
    input_text = f"write a 100-word blog post about {topic}: {description}"
    input_ids = tokenizer.encode(input_text, return_tensors="pt", max_length=512, truncation=True)
    outputs = model.generate(input_ids, max_length=200, num_beams=4, early_stopping=True)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def create_poster(title, content, theme="health", small=True):
    """Create a styled poster image"""
    base_width, base_height = 600, 900
    scale_factor = 0.75 if small else 1
    width, height = int(base_width * scale_factor), int(base_height * scale_factor)

    # Set colors based on theme
    if theme == "health":
        bg_color = (240, 248, 255)
        text_color = (0, 100, 0)
        accent_color = (0, 128, 0)
    elif theme == "tech":
        bg_color = (240, 240, 240)
        text_color = (25, 25, 112)
        accent_color = (0, 0, 128)
    else:  # travel
        bg_color = (255, 248, 220)
        text_color = (139, 69, 19)
        accent_color = (165, 42, 42)

    img = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(img)

    border_size = int(20 * scale_factor)
    draw.rectangle([border_size, border_size, width-border_size, height-border_size],
                  outline=accent_color, width=int(3 * scale_factor))

    try:
        title_font = ImageFont.truetype("arialbd.ttf", int(40 * scale_factor))
        subtitle_font = ImageFont.truetype("arial.ttf", int(20 * scale_factor))
        body_font = ImageFont.truetype("arial.ttf", int(16 * scale_factor))
    except IOError:
        title_font = ImageFont.load_default()
        subtitle_font = ImageFont.load_default()
        body_font = ImageFont.load_default()

    draw.text((width//2, int(75 * scale_factor)), title, fill=text_color, font=title_font, anchor="mm")
    subtitle = f"Latest Trends in {title}"
    draw.text((width//2, int(125 * scale_factor)), subtitle, fill=accent_color, font=subtitle_font, anchor="mm")

    text_width = width - 2 * int(50 * scale_factor)
    char_width = body_font.getlength("A")
    max_chars_per_line = int(text_width // char_width)
    lines = textwrap.wrap(content, width=max_chars_per_line)
    y_position = int(175 * scale_factor)
    line_height = int(20 * scale_factor)
    for line in lines:
        draw.text((int(50 * scale_factor), y_position), line, fill=text_color, font=body_font)
        y_position += line_height

    footer_height = int(50 * scale_factor)
    draw.rectangle([0, height-footer_height, width, height], fill=accent_color)
    draw.text((width//2, height-int(25 * scale_factor)), "Generated by AI Blog Poster",
             fill=bg_color, font=subtitle_font, anchor="mm")

    return img

# --- Streamlit App Start ---
st.set_page_config(page_title="AI Blog Poster Generator", layout="centered")
st.title("📄 AI Blog Poster Generator (Small Version)")
st.write("This app generates small, themed posters based on AI-generated blog content.")

output_dir = "blog_posters_small"
os.makedirs(output_dir, exist_ok=True)

for index, row in df.iterrows():
    st.markdown(f"## 🎯 {row['title']}")

    blog_content = generate_blog_content(row['title'], row['description'])
    poster = create_poster(row['title'], blog_content, theme=row['title'].lower(), small=True)

    buffered = BytesIO()
    poster.save(buffered, format="PNG")
    img_bytes = buffered.getvalue()

    st.image(img_bytes, caption=f"{row['title']} Poster", use_column_width=True)

    st.download_button(
        label=f"⬇️ Download {row['title']} Poster",
        data=img_bytes,
        file_name=f"{row['title'].lower()}_poster_small.png",
        mime="image/png"
    )

st.success("All posters generated and displayed with download links!")
